slam_toolbox:
  ros__parameters:
    mode: localization
    use_sim_time: true
    solver_plugin: solver_plugins::CeresSolver
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan
    minimum_travel_distance: 0.2
    minimum_travel_heading: 0.2
    map_update_interval: 5.0
    enable_interactive_mode: false
    map_start_at_dock: true
    # These stop new map data being added
    max_laser_range: 12.0
    throttle_scans: 1
    transform_publish_period: 0.02
    do_loop_closing: false
    loop_search_maximum_distance: 0.0